const RESOURCE_KEY_TAG = "[RESOURCE-KEY]";
const HEADERS_TAG = "[HEADERS]";
const BROWSER_TAG = "[BROWSER]";
const NODE_TAG = "[NODE]";
const SHARED_TAG = "[SHARED]";
const CROSSEENV_TAG = "[CROSSEENV]";
const DEPRECATION_TAG = "[DEPRECATION]";
const LEGACY_TAG = "[LEGACY]";
const PROMISE_TAG = "[PROMISE]";
const DOM_TAG = "[DOM]";
const INTEGRATION_TAG = "[INTEGRATION]";

export {
  LEGACY_TAG,
  RESOURCE_KEY_TAG,
  HEADERS_TAG,
  BROWSER_TAG,
  NODE_TAG,
  SHARED_TAG,
  CROSSEENV_TAG,
  DEPRECATION_TAG,
  PROMISE_TAG,
  DOM_TAG,
  INTEGRATION_TAG,
};
