import { EAPIErrors } from "./errors";
import {
  INVALID_RESOURCE_KEY_RESPONSE_MOCK,
  NON_EXISING_ON_SERVER_RESPONSE_MOCK,
  MISSING_USER_AGENT_RESPONSE_MOCK,
  REQUEST_LIMIT_REACHED_RESPONSE_MOCK,
  INTERNAL_SERVER_ERROR_RESPONSE_MOCK,
  HAPPY_CASE_USER_KEY_MOCK,
  HAPPY_CASE_DEFAULT_KEY_DATA_MOCK,
  HAPPY_CASE_DEFAULT_KEY_RESPONSE_MOCK,
} from "./api";

export {
  EAPIErrors,
  INVALID_RESOURCE_KEY_RESPONSE_MOCK,
  NON_EXISING_ON_SERVER_RESPONSE_MOCK,
  MISSING_USER_AGENT_RESPONSE_MOCK,
  REQUEST_LIMIT_REACHED_RESPONSE_MOCK,
  INTERNAL_SERVER_ERROR_RESPONSE_MOCK,
  HAPPY_CASE_USER_KEY_MOCK,
  HAPPY_CASE_DEFAULT_KEY_DATA_MOCK,
  HAPPY_CASE_DEFAULT_KEY_RESPONSE_MOCK,
};
