name: 'Publish package'

permissions:
  contents: write

env:
  USER_KEY_VALID: ${{ secrets.USER_KEY_VALID }}
  USER_KEY_INVALID: ${{ secrets.USER_KEY_INVALID }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter version'
        default: '2.0.0'
        required: false
        type: string

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Git Identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Clean cache
        run: yarn cache clean --force
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install
      - name: Run build
        run: yarn run build
      - name: Run tests
        run: yarn run test
      - name: Bump version
        run: yarn version --new-version ${{ inputs.version }} && git push
      - name: Create git tag
        run: |
          git tag -af v${{ inputs.version }} -m "Version ${{ inputs.version }}"
          git push --tags --force
      - name: Publish to NPM
        run: yarn publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}