name: ua-parser-js-run-test

on: [push, pull_request]

permissions:
  contents: read

env:
  USER_KEY_VALID: ${{ secrets.USER_KEY_VALID }}
  USER_KEY_INVALID: ${{ secrets.USER_KEY_INVALID }}

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run the test
        run: |
          yarn
          yarn test
